# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fbbc1341dc8147405223c5242518975d00f4905de8ec662e665bff64b87c37fbf79dbe25beb3cb6496d0e28734fa8489623be5a3a9f828d1a19c3a811013155

test:
  secret_key_base: ed77c4646b68a924f6b3e18c0e5c87e1c528a5e6d84600de03467cf47f4103458ee207586d580a7227d3cc8a17a57b073b261ead1670994d2665a8d91050f037

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
